[project]
name = "optic-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.23.3",
    "opencv-python>=4.12.0.88",
]
